:schedule:
  lock_trip_job:
    cron: '0 0 * * *'
    class: LockTripJobJob
:concurrency: 3
:timeout: 60
:verbose: true
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
